"use client";
import { useEditorStore } from "@/store/editor-store";
import type { AspectRatio, SafeZone } from "@/types/editor";
const ratios:[AspectRatio,string][]=[["original","Original"],["9:16","9:16"],["16:9","16:9"],["1:1","1:1"],["4:5","4:5"]];
const zones:[SafeZone,string][]=[["none","None"],["all","All"],["tiktok","TikTok"],["youtube","YouTube"],["instagram","Instagram"],["linkedin","LinkedIn"],["x","X"]];
export function ProjectPanel(){const c=useEditorStore(s=>s.canvas),set=useEditorStore(s=>s.setCanvas),versions=useEditorStore(s=>s.versions),save=useEditorStore(s=>s.saveVersion),restore=useEditorStore(s=>s.restoreVersion);return <aside className="project-panel">
<div className="inspector-section"><h3>Resize Project</h3><div className="ratio-grid">{ratios.map(([v,l])=><button key={v} className={c.aspectRatio===v?"on":""} onClick={()=>set({aspectRatio:v})}>{l}</button>)}</div></div>
<div className="inspector-section"><div className="setting-line"><b>Speaker Focus</b><button className={c.speakerFocus?"switch on":"switch"} onClick={()=>set({speakerFocus:!c.speakerFocus})}>{c.speakerFocus?"On":"Off"}</button></div><div className="setting-line"><b>Snap to Grid</b><button className={c.snapToGrid?"switch on":"switch"} onClick={()=>set({snapToGrid:!c.snapToGrid})}>{c.snapToGrid?"On":"Off"}</button></div></div>
<div className="inspector-section"><h3>Background</h3><div className="bg-control"><input type="color" value={c.backgroundColor} onChange={e=>set({backgroundColor:e.target.value})}/><input value={c.backgroundColor} onChange={e=>set({backgroundColor:e.target.value})}/></div><div className="swatches">{["#000000","#ffffff","#ff5b5b","#ffd84a","#42d37a","#38bdf8","#8b5cf6"].map(x=><button key={x} style={{background:x}} onClick={()=>set({backgroundColor:x})}/>)}</div><div className="setting-line"><b>Canvas Blur</b><button className={c.blur?"switch on":"switch"} onClick={()=>set({blur:!c.blur})}>{c.blur?"On":"Off"}</button></div></div>
<div className="inspector-section"><h3>Safe Zones</h3><div className="safe-grid">{zones.map(([v,l])=><button key={v} className={c.safeZone===v?"on":""} onClick={()=>set({safeZone:v})}>{l}</button>)}</div></div>
<div className="inspector-section"><h3>Expand Padding <span>{c.padding}%</span></h3><input type="range" min="0" max="24" value={c.padding} onChange={e=>set({padding:+e.target.value})}/><h3>Video Scale <span>{Math.round(c.videoScale*100)}%</span></h3><input type="range" min="60" max="160" value={c.videoScale*100} onChange={e=>set({videoScale:+e.target.value/100})}/></div>
<div className="inspector-section"><h3>Versions</h3><button className="wide-action" onClick={save}>Save current version</button><div className="version-list">{versions.map(v=><button key={v.id} onClick={()=>restore(v.id)}><b>{new Date(v.updatedAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</b><span>{v.captions.length} captions</span></button>)}</div></div>
</aside>}
